# Generated by go2rpm 1
%bcond_without check

# https://github.com/couchbase/vellum
%global goipath         github.com/couchbase/vellum
%global commit          ef2e028c01fdb60c46da4067d2e83745b8d54120

%gometa

%global common_description %{expand:
A Go library implementing an FST (finite state transducer).}

%global golicenses      LICENSE levenshtein/LICENSE
%global godocs          docs CONTRIBUTING.md README.md\\\
                        levenshtein/README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        A Go library implementing an FST (finite state transducer)

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/edsrzf/mmap-go)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(github.com/willf/bitset)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE levenshtein/LICENSE
%doc docs CONTRIBUTING.md README.md levenshtein/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Sun Jan 26 04:20:17 CET 2020 Marcel Metz <mmetz@adrian-broher.net> - 0-0.1.20200126gitef2e028
- Initial package
